export const initialCatalog = [
  {
    id: '1',
    title: 'Berserk',
    author: 'Kentaro Miura',
    genre: 'Dark Fantasy',
    year: 1989,
    status: 'READING',
  },
  {
    id: '2',
    title: 'Vagabond',
    author: 'Takehiko Inoue',
    genre: 'Historical',
    year: 1998,
    status: 'ON_HOLD',
  },
  {
    id: '3',
    title: 'Vinland Saga',
    author: 'Makoto Yukimura',
    genre: 'Historical',
    year: 2005,
    status: 'READING',
  },
  {
    id: '4',
    title: 'Solo Leveling',
    author: 'Chugong',
    genre: 'Action',
    year: 2018,
    status: 'COMPLETED',
  },
  {
    id: '5',
    title: 'Tower of God',
    author: 'SIU',
    genre: 'Adventure',
    year: 2010,
    status: 'READING',
  },
  {
    id: '6',
    title: 'Monster',
    author: 'Naoki Urasawa',
    genre: 'Thriller',
    year: 1994,
    status: 'COMPLETED',
  },
  {
    id: '7',
    title: 'Oyasumi Punpun',
    author: 'Inio Asano',
    genre: 'Drama',
    year: 2007,
    status: 'COMPLETED',
  },
  {
    id: '8',
    title: 'Chainsaw Man',
    author: 'Tatsuki Fujimoto',
    genre: 'Action',
    year: 2018,
    status: 'READING',
  },
  {
    id: '9',
    title: 'Blame!',
    author: 'Tsutomu Nihei',
    genre: 'Sci-Fi',
    year: 1997,
    status: 'PLAN_TO_READ',
  },
  {
    id: '10',
    title: 'The Beginning After The End',
    author: 'TurtleMe',
    genre: 'Fantasy',
    year: 2018,
    status: 'READING',
  },
];
